name: Deploy Node.js app to Azure Web App - synth-speech

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a version that is compatible with your project

      - name: npm install
        run: |
          npm install
          npm audit fix --force # Attempt to fix vulnerabilities

      - name: Start Node.js application
        run: |
          npm start &
          
  deploy-to-azure:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'synth-speech'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EA3F3676B7F4327AA370BFB78FD6090 }}
          package: .
